name: MSYS2 build (MinGW-w64)

on:
  pull_request:
  push:
    paths-ignore:
      - '.github/workflows/coverage.yml'
      - '.github/workflows/linux-build.yml'
      - '.github/workflows/macos-build.yml'
      - '.github/workflows/wasm-build.yml'
      - '.github/workflows/windows-build.yml'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'README.md'
      - 'README_en.md'
      - 'README_fr.md'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        mode: [debug, releasedbg]
        confs:
        - { msystem: mingw32, arch: i686,   config_build: "",                         config_install: "" } # Qt and FFMpeg package doesn't support 32bits
        - { msystem: mingw64, arch: x86_64, config_build: --shadernodes=y --ffmpeg=y, config_install: --shadernodes=y }

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Get current date as package key
      id: cache_key
      shell: bash
      run: echo "key=$(date +'%W')" >> $GITHUB_OUTPUT

    - name: Checkout repository
      uses: actions/checkout@v4

    # Setup MSYS2
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.confs.msystem }}
        install: base-devel git unzip p7zip mingw-w64-${{ matrix.confs.arch }}-toolchain mingw-w64-${{ matrix.confs.arch }}-xmake
        update: true

    # Force xmake to a specific folder (for cache)
    - name: Set xmake env
      run: echo "XMAKE_GLOBALDIR=${{ runner.workspace }}/xmake-global" >> $GITHUB_ENV

    # Update xmake repository (in order to have the file that will be cached)
    - name: Update xmake repository
      run: xmake repo --update

    # Fetch xmake dephash
    - name: Retrieve dependencies hash
      id: dep_hash
      run: echo "hash=$(xmake l utils.ci.packageskey)" >> $GITHUB_OUTPUT
  
    # Cache xmake dependencies
    - name: Retrieve cached xmake dependencies
      uses: actions/cache@v3
      with:
        path: ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
        key: MinGW-${{ matrix.confs.arch }}-${{ matrix.mode }}-${{ steps.dep_hash.outputs.hash }}-W${{ steps.cache_key.outputs.key }}

    # Setup compilation mode and install project dependencies
    - name: Configure xmake and install dependencies
      run: xmake config --arch=${{ matrix.confs.arch }} --mode=${{ matrix.mode }} --ccache=n --tests=y --unitybuild=y --yes ${{ matrix.confs.config_build }}

    # Build the engine
    - name: Build Nazara
      run: xmake --yes

    # Run unit tests
    - name: Run unit tests
      if: matrix.mode != 'releasedbg'
      run: xmake run UnitTests

    # Setup installation configuration
    - name: Configure xmake for installation
      run: xmake config --arch=${{ matrix.confs.arch }} --mode=${{ matrix.mode }} --ccache=n --ffmpeg=n --tests=y --yes ${{ matrix.confs.config_install }}

    # Install the result files
    - name: Install Nazara
      run: xmake install -vo package

    # Upload artifacts
    - uses: actions/upload-artifact@v3
      with:
        name: nazaraengine-${{ matrix.os }}-${{ matrix.confs.arch }}-${{ matrix.mode }}
        path: package
